version: 2
updates:
- package-ecosystem: nuget
  directory: "/backend/"
  schedule:
    interval: monthly
  groups:
    backend-group:
      patterns:
        - "*"

- package-ecosystem: npm
  directory: "/frontend/"
  schedule:
    interval: monthly
  groups:
    frontend-group:
      patterns:
        - "*"

- package-ecosystem: devcontainers
  directory: "/backend/"
  schedule:
    interval: monthly

- package-ecosystem: devcontainers
  directory: "/frontend/"
  schedule:
    interval: monthly
